# Generated by Django 5.0 on 2023-12-06 16:35

import django.db.models.deletion
import django.db.models.fields.related
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
        migrations.AddField(
            model_name='comments',
            name='task',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tasks.task'),
        ),
        migrations.AddField(
            model_name='taskstatus',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.fields.related.OneToOneField, to='tasks.task'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['text'], name='tasks_task_text_6de00a_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['author'], name='tasks_task_author__52d8b9_idx'),
        ),
        migrations.AddIndex(
            model_name='comments',
            index=models.Index(fields=['text'], name='tasks_comme_text_cb6f45_idx'),
        ),
        migrations.AddIndex(
            model_name='comments',
            index=models.Index(fields=['task'], name='tasks_comme_task_id_1c072c_idx'),
        ),
        migrations.AddIndex(
            model_name='taskstatus',
            index=models.Index(fields=['status'], name='tasks_tasks_status_83658d_idx'),
        ),
        migrations.AddIndex(
            model_name='taskstatus',
            index=models.Index(fields=['task'], name='tasks_tasks_task_id_7abb14_idx'),
        ),
    ]
